<a href="https://colab.research.google.com/github/elessardari/IDC-MaIE_2026A/blob/main/ICD_Taller1_python_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **¡¡ ANTES DE EMPEZAR !!**

Deshabilita autocompletar con IA. Esta acción te ayudará a aprender de verdad. Si estás en Colab sigue estos pasos:



1.   Ir a Herramientas \ Configuración \ Asistencia de IA
2.   Desactivar la casilla **"Mostrar autocompletado impulsado por IA"**
3.   Activar la casilla **"Ocultar funciones de IA generativa"**

# **MÓDULO 0: PRIMEROS PASOS CON PYTHON**

Es común usar Excel para analizar datos, pero si el número de datos es grande, Excel se queda corto. En este caso, es conveniente movernos hacia una herramienta más sofisticada, como Python (el lenguaje de programación que usaremos en el curso). Entonces, antes de analizar datos complejos, debemos entender Python. Por fortuna, es un lenguaje muy legible, muy parecido a Matlab.


**0.1 Variables:** En Excel, guardamos datos en celdas (A1, B2). En Python, usamos variables.

In [ ]:
# --- VARIABLES ---

# Asignamos variables con el signo '='
# No necesitamos declarar el tipo (int, float); Python lo infiere.

voltaje = 220       # Entero (int)
resistencia = 10.5  # Decimal (float)
sistema_activo = True # Booleano (lógica binaria: 1 o 0)
nombre_pozo = "Pozo Norte-X" # Texto (string)

# La función print() muestra el resultado en pantalla
print("El voltaje es:", voltaje)

# La función type() nos dice qué tipo de dato es
print("Tipo de dato de resistencia:", type(resistencia))

El voltaje es: 220
Tipo de dato de resistencia: <class 'float'>

**0.2 Operaciones Matemáticas y Librerías:** Al igual que Matlab, Python funciona como una calculadora científica:

In [ ]:
# --- CÁLCULOS EN PYTHON ---

# Ley de Ohm: I = V / R
corriente = voltaje / resistencia

# Potencia: P = V * I
potencia = voltaje * corriente

print("La corriente calculada es", corriente, "Amperios")
print("La potencia es:", potencia, "Watts")

La corriente calculada es 20.952380952380953 Amperios
La potencia es: 4609.523809523809 Watts

A diferencia de Matlab, la mayoría de funciones de Python están en librerías, y antes de usarlas, debemos importar esas librerías:

In [ ]:
# --- LIBRERÍAS ---

# Calculemos el voltaje a partir de la potencia y la resistencia.
# Para ello debemos usar la función "raíz cuadrada", sqrt().
# Esta función está disponible en la librería "math", así que primero debemos importar esta librería.
# Además, podemos darle nombre un "alias" personalizado a la librería, por ejemplo "matem"

import math as matem

# Voltaje calculado: voltaje_calculado = sqrt(potencia*resistencia)
voltaje_calculado = matem.sqrt(potencia*resistencia)

print(f"El voltaje calculado es: {voltaje_calculado:.2f} Voltios") #.2f se usa para mostrar 2 decimales

El voltaje calculado es: 220.00 Voltios

**0.3 Estructuras de Datos: Listas y Diccionarios:**
En ingeniería rara vez trabajamos con un solo dato; trabajamos con vectores o series. En Python, usamos listas (que definimos usando corchetes []) y diccionarios (definidas usando llaves {}).

Las listas son los "vectores" de Pyhton; es decir, colecciones ordenadas indexadas por posición (0,1,2...). Por otro lado, los diccionarios son colecciones desordenadas de pares "llave"-"valor".

**Nota:** En Python, los elementos de las listas se empiezan a contar desde CERO, no desde uno.

In [ ]:
# --- LISTAS (VECTORES) ---

# Una lista de temperaturas tomadas por un sensor en 5 momentos distintos
temperaturas = [105.4, 106.2, 108.1, 107.5, 110.0]

# Acceder al primer dato (índice 0)
print("Temperatura inicial:", temperaturas[0])

# Acceder al último dato (índice -1)
print("Temperatura final:", temperaturas[-1])

# ¿Cuántos datos tenemos?
print("Número de mediciones:", len(temperaturas)) #la función len() devuelve el número de elementos de la lista

# Operaciones básicas: Agregar un dato nuevo
temperaturas.append(24.1) #el método .append() agrega un elemento al final de la lista
print("Lecturas actualizadas:", temperaturas)

Temperatura inicial: 105.4
Temperatura final: 110.0
Número de mediciones: 5
Lecturas actualizadas: [105.4, 106.2, 108.1, 107.5, 110.0, 24.1]

In [ ]:
# --- DICCIONARIOS (LLAVE-VALOR) ---

# Describamos con un diccionario las propiedades de una turbina
turbina_1 = {
    "id": "T-001",
    "ubicacion": "Sala de Máquinas A",
    "rpm_actual": 3600,
    "temperatura_aceite": 85.5,
}

print("Información de la turbina:", turbina_1)
print("RPM de la turbina:", turbina_1["rpm_actual"])

Información de la turbina: {'id': 'T-001', 'ubicacion': 'Sala de Máquinas A', 'rpm_actual': 3600, 'temperatura_aceite': 85.5}
RPM de la turbina: 3600

**0.4 Identación, Condicionales (if, else) y Ciclos (for):**
A diferencia de otros lenguajes que usan llaves {} para agrupar código, Python utiliza la indentación (sangría). Es obligatorio, no estético.

Cada vez que una línea termina en dos puntos (:), la siguiente línea debe tener identación (usualmente 4 espacios). Todo el código que comparte el mismo nivel de indentación pertenece al mismo bloque lógico.

In [ ]:
# --- CONDICIONALES ---

import random # importamos la librería random

retorno_diario = -random.randint(1, 10) # simulamos una caída aleatoria entre el 10% y 1%
print(f"retorno: {retorno_diario} %")

# Noten los dos puntos (:) al final de la línea 'if'
# Noten el espacio (4 espacios o 1 TAB) en las líneas print
if retorno_diario < -5:
    print("ALERTA: Caída significativa detectada.") # esta línea se ejecuta si es TRUE porque está identada respecto al "if"
    print("Revisar noticias macroeconómicas.") # esta línea también se ejecuta si es TRUE porque está identada
else:
    print("Mercado estable.") # esta línea se ejecuta si es FALSE porque está identada respecto al "else"

print("Fin del análisis.") # Esta línea se ejecuta SIEMPRE, porque no tiene indentación.

retorno: -3 %
Mercado estable.
Fin del análisis.

In [ ]:
# --- CICLOS ---

# Caso1: Usemos un ciclo for para operar sobre una lista
precios_USD = [100, 102, 98, 105, 110] # lista de precios en dolares
precios_COP = []

# "Para cada 'precio' dentro de la lista 'precios'..."
for precio in precios_USD:
    # Lo convertimos a pesos (multiplicamos por 3650)
    precio_COP = precio*3650
    precios_COP.append(precio_COP)

print("Lista de precios en pesos es", precios_COP)

Lista de precios en pesos es [365000, 372300, 357700, 383250, 401500]

In [ ]:
# Caso 2: Si no tienes una lista, pero quieres repetir algo 5 veces, usas la función range()
for numero in range(5): # range(5) crea una secuencia: 0, 1, 2, 3, 4
    print(f"Vuelta número: {numero}")

Vuelta número: 0
Vuelta número: 1
Vuelta número: 2
Vuelta número: 3
Vuelta número: 4

In [ ]:
# Caso 3: Usemos ahora un ciclo for para operar sobre un diccionario
ventas = {
    "Lunes": 100,
    "Martes": 250,
    "Miércoles": 180
}

# Si queremos recorrer el diccionario sobre las LLAVES:
for dia in ventas.keys():
  print(f"El día {dia} se registraron ventas")

# Si queremos recorrer el diccionario sobre los VALORES:
total_ventas = 0
for valor in ventas.values():
  total_ventas = total_ventas + valor
print(f"El total de ventas de la semana fue {total_ventas}")

El día Lunes se registraron ventas
El día Martes se registraron ventas
El día Miércoles se registraron ventas
El total de ventas de la semana fue 530

**Nota:** Aunque el ciclo for es fundamental para entender la lógica, en Ciencia de Datos intentamos evitarlo cuando procesamos millones de datos. Preferimos la "vectorización" (operar sobre toda la columna a la vez). Esto lo veremos en el Módulo 1 (Pandas).

# Reto 1 (motor industrial):
Tienes una lista de lecturas crudas provenientes de un sensor de vibración en un motor industrial. Sin embargo, el sensor a veces falla y arroja valores negativos (ruido/error) o valores extremadamente altos (posible falla crítica). Tu tarea es implementar un código que haga lo siguiente:


* Crea una lista con los datos válidos (aquellos que no son negativos)
* Calcula el valor $RMS$ de los datos válidos y "normales", ignorando aquellos que son mayores que 100 (estos corresponden a posibles fallas crítica del motor). Recuerda que $RMS = \sqrt{\frac{x^2}{n}}$.
* Finalmente, crea un diccionario llamado "reporte" que contenga:
    * la lista de datos válidos
    * el total de datos válidos
    * el total de alertas críticas
    * el valor RMS calculado
* Imprime el reporte

In [ ]:
# --- DATOS DE ENTRADA (NO MODIFICAR) ---
lecturas_vibracion = [10.5, 12.1, -5.0, 11.8, 105.4, 13.2, -1.2, 12.5, 11.0, 9.8]

# --- TU CÓDIGO EMPIEZA AQUÍ ---

# Reto 2 (controlador de batería):


Eres el ingeniero a cargo de una micro-red eléctrica que alimenta una fábrica. Tienes paneles solares y una batería de respaldo. Tu objetivo es minimizar el costo de la energía comprada a la red externa simulando 10 horas de operación.

**Reglas del Sistema:**

1.  Si en cierta hora hay excedente de generación:
    * La energía sobrante carga la batería.
    * La batería no puede superar los 50 KWh. Si se llena, el resto se pierde.
3.  Si hay déficit de generación:
    * La energía faltante se toma primero de la batería.
    * Si la batería se agota (o no alcanza), la diferencia se compra a la red eléctrica.
    * La batería no puede quedar con carga negativa (mínimo 0 kWh).
4.  Las tarifas de la energía de la red son dinámicas:
    * El costo en horario pico (10:00 am, 11:00 am y 12:00 m) es de 500 COP/kWh.
    * En hora valle (resto de horas), el costo es de 200 COP/kWh.

**Objetivo:**
Recorre las listas, aplica la lógica hora por hora y genera un diccionario final con el reporte de los resultados acumulados.

In [ ]:
# --- DATOS DE ENTRADA (NO MODIFICAR) ---
# La resolución de los datos es horaria empezando desde las 7:00 am
generacion = [15.0, 20.0, 45.0, 55.0, 60.0, 40.0, 25.0, 10.0, 5.0, 0.0] # kWh producidos
consumo    = [10.0, 15.0, 20.0, 70.0, 80.0, 50.0, 40.0, 25.0, 20.0, 10.0] # kWh consumidos

# --- PARÁMETROS DEL SISTEMA ---
capacidad_bateria = 50.0  # kWh máximos
carga_actual      = 10.0  # La batería inicia con 10 kWh
dinero_gastado    = 0.0   # Acumulador de dinero

# historial de carga de la batería
historial_bateria = []

# --- TU CÓDIGO EMPIEZA AQUÍ ---


# --- REPORTE FINAL ---
reporte = {
    "Costo Total Operación ($)": dinero_gastado,
    "Carga Final Batería (kWh)": carga_actual,
    "Historial Batería": historial_bateria
}

print("--- REPORTE DE GESTIÓN ENERGÉTICA ---")
print(reporte)

--- REPORTE DE GESTIÓN ENERGÉTICA ---
{'Costo Total Operación ($)': 0.0, 'Carga Final Batería (kWh)': 10.0, 'Historial Batería': []}

# **MÓDULO 1: PANDAS**

Las listas y diccionarios de Python son útiles, pero para trabajar con datos a un nivel más avanzado necesitamos algo más eficiente. Aquí entra Pandas, una librería de Python diseñada para trabajar con datos.

Pandas introduce el DataFrame: Es una tabla con etiquetas (filas y columnas), donde los tipos de datos están optimizados para manejar millones de registros. Es como una hoja de Excel, pero eficiente y programable. Además, en un DataFrame se pueden almacenar datos de diferentes tipos: números, fechas, strings, etc.


**1.1 Preliminares:**
Primero, importamos la librería y descargamos los datos con los que trabajaremos: el comportamiento del S&P 500, un indicador del estado de la economía mundial.

In [ ]:
# --- IMPORTACIÓN DE PANDAS Y CARGA DE DATOS ---

import pandas as pd # Importamos la librería con el alias 'pd' (estándar mundial)
import yfinance as yf # Librería Yahoo Finance, para descargar datos financieros reales

# Descargamos datos históricos del índice S&P 500 (desde 1990 hasta 2025)
print("Descargando dataset...")
datos_crudos = yf.download("^GSPC", start="1990-01-01", end="2025-12-31")

# Veamos cómo son los datos que acabamos de descargar:
print(datos_crudos.head()) # .head muestra las primeras 5 filas de los datos descargados

# Exportemos a formato .CSV los datos de cierre de mercado 'Close'para simular la lectura de un archivo local
datos_crudos['Close'].to_csv('sp500_history.csv') # .to_csv() crea el archivo sp500_history.csv
print("Archivo 'sp500_history.csv' generado exitosamente.")

Descargando dataset...

/tmp/ipython-input-980011720.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  datos_crudos = yf.download("^GSPC", start="1990-01-01", end="2025-12-31")
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker           ^GSPC       ^GSPC       ^GSPC       ^GSPC      ^GSPC
Date
1990-01-02  359.690002  359.690002  351.980011  353.399994  162070000
1990-01-03  358.760010  360.589996  357.890015  359.690002  192330000
1990-01-04  355.670013  358.760010  352.890015  358.760010  177000000
1990-01-05  352.200012  355.670013  351.350006  355.670013  158530000
1990-01-08  353.790009  354.239990  350.540009  352.200012  140110000
Archivo 'sp500_history.csv' generado exitosamente.

**1.2 Carga e Inspección:**
Ahora utilizaremos la función `read_csv` de la librería Pandas para cargar el archivo en un DataFrame.

In [ ]:
# --- CREACIÓN DEL DataFrame ---

# Creamos el DataFrame llamado "mercado" con la función de PANDAS .read_csv()
mercado = pd.read_csv('sp500_history.csv')
print("DataFrame 'mercado' generado exitosamente.")

DataFrame 'mercado' generado exitosamente.

Las columnas y filas de los **DataFrames** tienen etiquetas que nos ayudan a identificarlas:

* **Etiquetas de columna:** Generalmente son los nombres de las variables almacenadas (ej. `Edad`, `Precio`).
* **Etiquetas de fila (Índice):** Actúan como el identificador único de cada fila. Comúnmente son números consecutivos, pero también pueden ser fechas (en series temporales) o textos específicos.

Una característica clave es que las columnas pueden almacenar **diferentes tipos de datos**. Por ejemplo, la primera columna puede contener números enteros y la segunda cadenas de texto (*strings*).

In [ ]:
# --- EXPLORACIÓN DE CARACTERÍSTICAS DEL DataFrame ---

print(f"Dimensiones: {mercado.shape}") # .shape devuelve (número de filas, número de columnas)
display(mercado.head()) # .head muestra las primeras 5 filas

print("\n--- INFORMACIÓN GENERAL ---")
print(mercado.info()) # .info() muestra tipos de datos y memoria

print("\n--- NOMBRES DE COLUMNAS ---")
print(mercado.columns) # Muestra los nombres de las variables

print("\n--- ÍNDICE (ETIQUETAS DE FILAS) ---")
print(mercado.index) # Muestra cómo están etiquetadas las filas

# Acceder a una fila específica por su POSICIÓN (usamos .iloc)
print("\n--- DATO EN LA FILA 100 ---")
fila_100 = mercado.iloc[99] # Recordar: Python cuenta desde 0, así que la fila 100 es el índice 99
print(fila_100)

# Si solo queremos ver la fecha de esa fila:
print(f"\nFecha de la fila 100: {mercado.iloc[99]['Date']}")

Dimensiones: (9066, 2)

         Date       ^GSPC
0  1990-01-02  359.690002
1  1990-01-03  358.760010
2  1990-01-04  355.670013
3  1990-01-05  352.200012
4  1990-01-08  353.790009

--- INFORMACIÓN GENERAL ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9066 entries, 0 to 9065
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9066 non-null   object
 1   ^GSPC   9066 non-null   float64
dtypes: float64(1), object(1)
memory usage: 141.8+ KB
None

--- NOMBRES DE COLUMNAS ---
Index(['Date', '^GSPC'], dtype='object')

--- ÍNDICE (ETIQUETAS DE FILAS) ---
RangeIndex(start=0, stop=9066, step=1)

--- DATO EN LA FILA 100 ---
Date     1990-05-23
^GSPC    359.290009
Name: 99, dtype: object

Fecha de la fila 100: 1990-05-23

**1.3 Manipulación del DataFrame:** Los datos rara vez vienen limpios o en el formato que queremos. Aquí simularemos un proceso de pre-procesamiento del DataFrame

In [ ]:
# --- CAMBIO DE ETIQUETAS DE LAS COLUMNAS DEL DataFrame ---

# Vamos a renombrar las columnas de nuestro DataFrame "mercado". La primera la etiquetaremos como "fecha" y la segunda como "precio"
mercado.rename(columns={'Date': 'fecha', '^GSPC': 'precio'}, inplace=True) # El parámetro inplace=True hace que el cambio se guarde en el mismo DataFrame.
display(mercado.head()) # .head muestra las primeras 5 filas

# Alternativa a inplace=True:
mercado = mercado.rename(columns={'Date': 'fecha', '^GSPC': 'precio'})

        fecha      precio
0  1990-01-02  359.690002
1  1990-01-03  358.760010
2  1990-01-04  355.670013
3  1990-01-05  352.200012
4  1990-01-08  353.790009

In [ ]:
# --- CAMBIO DE ÍNDICES (FILAS) DEL DataFrame ---
# Como nuestros datos son una serie temporal, es conveniente etiquetar las filas con la fecha en lugar de usar un número

# Convertimos la columna a formato fecha (importante para que Pandas entienda que son fechas y no texto)
mercado['fecha'] = pd.to_datetime(mercado['fecha'])

# Establecemos la columna 'fecha' como el índice
mercado_ind = mercado.set_index('fecha', drop=False) # Usamos drop=False para mantener la columna "fecha" (aunque es redundante...¿Por qué?)
display(mercado_ind.head()) # .head muestra las primeras 5 filas

                fecha      precio
fecha
1990-01-02 1990-01-02  359.690002
1990-01-03 1990-01-03  358.760010
1990-01-04 1990-01-04  355.670013
1990-01-05 1990-01-05  352.200012
1990-01-08 1990-01-08  353.790009

In [ ]:
# --- CONSULTA POR ETIQUETA ---

# Definimos una fecha de interés (debe tener el formato 'AAAA-MM-DD')
fecha_interes = '2020-03-16'

# Usamos .loc[fila, columna] para buscar por ETIQUETA
# Fila = fecha_interes
# Columna = 'precio'
valor = mercado_ind.loc[fecha_interes, 'precio']

print(f"El precio del S&P 500 el día {fecha_interes} fue: {valor}")

El precio del S&P 500 el día 2020-03-16 fue: 2386.1298828125

# **MÓDULO 2: ANÁLISIS VECTORIZADO**

Aquí sustituimos los ciclos `for` por operaciones aplicadas a columnas enteras.


**2.1 Creación de Variables (Feature Engineering):** Para analizar una serie de tiempo (financiera, demográfica o climática), el valor absoluto importa menos que la variación porcentual.
$$
  \text{variacion}=\frac{\text{precio_actual}-\text{precio_ayer}}{\text{precio_ayer}}
$$

In [ ]:
# --- VECTORIZACIÓN ---

# Pandas aplica la operación a las 9,000 filas instantáneamente.
# .shift(1) mueve los datos una posición hacia abajo (el precio de ayer).

mercado_ind['precio_ayer'] = mercado_ind['precio'].shift(1)

# Calculamos variación porcentual de forma manual (para entender la matemática)
mercado_ind['variacion'] = (mercado_ind['precio'] - mercado_ind['precio_ayer']) / mercado_ind['precio_ayer']

# Forma optimizada de Pandas (hace lo mismo que arriba)
mercado_ind['variacion'] = mercado_ind['precio'].pct_change()

# Limpiamos los datos nulos generados por el shift (la primera fila no tiene "ayer")
mercado_ind.dropna(inplace=True)

mercado_ind.head()

                fecha      precio  precio_ayer  variacion
fecha
1990-01-03 1990-01-03  358.760010   359.690002  -0.002586
1990-01-04 1990-01-04  355.670013   358.760010  -0.008613
1990-01-05 1990-01-05  352.200012   355.670013  -0.009756
1990-01-08 1990-01-08  353.790009   352.200012   0.004514
1990-01-09 1990-01-09  349.619995   353.790009  -0.011787

**2.2 Filtrado con Lógica Booleana: ** En lugar de un `if` dentro de un `for`, usamos filtros vectorizados.

Vamos a ver cuáles han sido los "Cisnes Negros" (eventos extremos negativos). Es decir, eventos donde el mercado ha caído más del 5% en un día

In [ ]:
# --- FILTRADO ---
# Definimos un umbral: caída mayor al 5%
umbral_crisis = -0.05

# Filtro: Esto devuelve un DataFrame sólo con las filas que cumplen la condición
crisis = mercado_ind[mercado_ind['variacion'] < umbral_crisis]

print(f"Se encontraron {len(crisis)} eventos extremos en el periodo.")
# Mostramos los 10 peores Cisnes Negros
print(crisis.sort_values(by='variacion', ascending=True).head(10))

Se encontraron 22 eventos extremos en el periodo.
                fecha       precio  precio_ayer  variacion
fecha
2020-03-16 2020-03-16  2386.129883  2711.020020  -0.119841
2020-03-12 2020-03-12  2480.639893  2741.379883  -0.095113
2008-10-15 2008-10-15   907.840027   998.010010  -0.090350
2008-12-01 2008-12-01   816.210022   896.239990  -0.089295
2008-09-29 2008-09-29  1106.420044  1213.270020  -0.088068
2008-10-09 2008-10-09   909.919983   984.940002  -0.076167
2020-03-09 2020-03-09  2746.560059  2972.370117  -0.075970
1997-10-27 1997-10-27   876.989990   941.640015  -0.068657
1998-08-31 1998-08-31   957.280029  1027.140015  -0.068014
2008-11-20 2008-11-20   752.440002   806.580017  -0.067123

# Reto Final (análisis del mercado global)


1.  **Cisnes Negros:**
    Observa la lista de los "Cisnes Negros" que generaste en el código anterior (las peores caídas del mercado). Elige **dos fechas** de esa lista e investiga qué pasó ese día en el mundo.
    * *Entregable:* Escribe un breve comentario de texto explicando la causa de esas dos caídas.

2.  **Cisnes Blancos:**
    Un "Cisne Blanco" en este contexto sería un día de altos retornos positivos, mayores a 5%.
    * Investiga el día más alcista de la historia (el top 1): ¿Fue un día marcado por un evento en particular o fue un "rebote" justo después de una gran caída?

3.  **Volatilidad:**
    En finanzas, la estabilidad es clave. Un mercado que sube y baja violentamente es "riesgoso".
    * Calcula la **Volatilidad Móvil de 30 días**.
    * *Pista:* Investiga el método `.rolling(window=30).std()` de Pandas. Esto calcula la desviación estándar (ruido) de los últimos 30 días para cada fecha.
    * Encuentra la **fecha** donde la volatilidad alcanzó su máximo histórico. ¿Coincide con alguna crisis conocida?

In [ ]:
# --- CÓDIGO CISNES BLANCOS ---

In [ ]:
# --- CÓDIGO VOLATILIDAD ---